# Generated by Django 3.0.2 on 2020-01-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('location', models.CharField(max_length=300)),
                ('num_people', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pph', models.IntegerField()),
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='event_user_junction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteer.event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteer.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteer.organization'),
        ),
    ]
