# Generated by Django 3.0.2 on 2020-01-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20200126_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
    ]
