# Generated by Django 3.0.2 on 2020-01-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_auto_20200126_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
