# Generated by Django 3.0.2 on 2020-01-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_auto_20200126_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event_user_junction',
        ),
    ]
